spring:
  h2:
    console:
      path: /h2-console
      enabled: "true"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: "true"
  datasource:
    username: ${DB_USER}
    password: ""
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL